apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fhomet/ArgoCDtest.git
    targetRevision: HEAD
    path: apps/external-secrets-store
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
