apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: v0.18.2
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
