resources:
  - ../../../../base/infra/external-secrets

patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: external-secrets
  patch: |-
    - op: add
      path: /spec/source/helm/values
      value: |-
        replicaCount: 1
        logLevel: debug