apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-app-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: test-app-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config: |
          El valor de los secrets es:

          user: {{ .username }}
          password: {{ .password }}
  data:
    - secretKey: username
      remoteRef:
        key: owgw-db-user-secret
        property: username
    - secretKey: password
      remoteRef:
        key: owgw-db-user-secret
        property: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: app
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          volumeMounts:
            - name: secret-vol
              mountPath: /etc/test
              readOnly: true
      volumes:
        - name: secret-vol
          secret:
            secretName: test-app-secret
