apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@projects.galgus.net:10443/devops/gcm-gen3-argocd.git
    targetRevision: main
    path: apps/dev/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd