apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com/fhomet/ArgoCDtest.git
    targetRevision: main
    path: apps/dev/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
